// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLWi2A_pGqP8NILEPbhiapKEFMqWDuJo',
    appId: '1:420815552861:web:e27630368864e2e6dc68b4',
    messagingSenderId: '420815552861',
    projectId: 'taskorganizer-83500',
    authDomain: 'taskorganizer-83500.firebaseapp.com',
    storageBucket: 'taskorganizer-83500.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkUH7jw6mvY8I-4wHhSQ1dgltZ-QWB9aA',
    appId: '1:420815552861:android:f2d03aaa61096047dc68b4',
    messagingSenderId: '420815552861',
    projectId: 'taskorganizer-83500',
    storageBucket: 'taskorganizer-83500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAonm5d1prNsND5kiiQikdXvkQEh4_YHa8',
    appId: '1:420815552861:ios:a62fc0bf0eb258bedc68b4',
    messagingSenderId: '420815552861',
    projectId: 'taskorganizer-83500',
    storageBucket: 'taskorganizer-83500.firebasestorage.app',
    iosBundleId: 'com.example.taskorganizer',
  );
}
